### PR TITLE
Update BuildToolsVersion to 1.0.26-prerelease-00513-03

### PR DESCRIPTION
**Pull request by maririos**
This is in preparation to consume the executor tool (PR #672 ) in the Build Tools repo.

cc: @weshaggard @joperezr @karajas

### CODE REVIEW

**Comment by maririos** [comment]
Currently the build tools test are broken. With this update we fix that.

**Comment by joperezr** [comment]
I'm not sure why we don't have tests enabled on CI, that seems wrong to me. Also, I checked and our VSO build also skips tests and I don't know why either. @jhendrixMSFT is there any reason for that? if not I can go ahead and change that so that we can catch breaks like this one.

**Comment by joperezr** [comment]
LGTM

**Comment by maririos** [comment]
I asked @mmitche about it and the condition in the CI was introduced when there were no tests so the build failed otherwise.
Now that we have tests, I can change the groovy file to run the tests in our CI.

**Comment by mmitche** [comment]
@maririos Yeah, do that.  I think that it's honestly been there for as long as buildtools has been a repo on dotnet-ci

**Comment by maririos** [comment]
PR #804 created

**Comment by joperezr** [comment]
(Now that the CI change has been made, re-running the CI to make sure that this change fixes the build break)

@dotnet-bot test this please

**Pull request merged**
