### PR TITLE
Include the target files in the build tasks project for easier browsing/...

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Simple change so the targets will show up in the Solution Explorer in VS.

### CODE REVIEW

**Comment by weshaggard** [comment]
Thanks @JeremyKuhne we originally did have these listed in VS but the list kept getting stale as we added more so I ended up removing them. Perhaps we can just wildcard them to avoid that issue and still have them easily available in VS.

**Comment by JeremyKuhne** [comment]
Good idea. I'll mull it over and perhaps make that change later. If the IDE supported it better it would be an absolute no brainer. Unfortunately it always breaks the wildcard into single item entries if you add/remove within the IDE...

**Comment by weshaggard** [comment]
While considering that we should also consider using wildcards to specify the list in the nuspec https://github.com/dotnet/buildtools/blob/master/src/nuget/Microsoft.DotNet.BuildTools.nuspec. The less explicit lists we have to maintain the less likely we are to cause issues.

**Comment by JeremyKuhne** [comment]
Going to update to wildcards.

**Pull request closed without merging**
