### PR TITLE
Release/1.0.0 Add version info to packages

### PR DESCRIPTION
**Pull request by chcosta**
Cherry-pick these commits to enable adding commit SHA information to built packages

https://github.com/dotnet/buildtools/commit/197567b4486eb655ccf00a40b3a5845980db15c4
https://github.com/dotnet/buildtools/commit/52868ab2f035e75165b8d78adf569e4066a06e1d

@weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
Is there someone specifically asking for this change in the 1.0.0 release branch?

**Comment by chcosta** [comment]
No one specifically is asking for it in 1.0.0. There is a request for the information in 1.1.0.

dotnet/corefx#12294 (comment)

My preference is to have it in both, but I don't really have a compelling reason.

**Comment by weshaggard** [comment]
>My preference is to have it in both, but I don't really have a compelling reason.

If we are going to do a buildtools update then I'm good but I would prefer not update the buildtools in the release branch if we don't have to.

**Comment by chcosta** [comment]
Ack, I'll close this for now.

**Pull request closed without merging**
