### PR TITLE
Switch to Jenkins-CI links.

### PR DESCRIPTION
**Pull request by mmitche**
Test for Jenkins PR testing

### CODE REVIEW

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/BuildTools_Build/6/
Test FAILed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/BuildTools_Build/7/
Test PASSed.

**Comment by mmitche** [comment]
Okay this is for real then.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/BuildTools_Build/8/
Test FAILed.

**Comment by weshaggard** [comment]
@mmitche I get a 404 when I click on those links. Is that expected?

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_buildtools_prtest/1/
Test PASSed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_buildtools_prtest/3/
Test PASSed.

**Comment by mmitche** [comment]
Yes, I am changing around the job names right now to be a little clearer since it looks like we have to have separate PR and non PR jobs.

**Comment by mmitche** [comment]
Yes, I am changing around the job names right now to be a little clearer since it looks like we have to have separate PR and non PR jobs.

**Pull request merged**
