### PR TITLE
Remove DotnetCLIVersion.txt, no longer used

### PR DESCRIPTION
**Pull request by dagood**
Bootstrap init flow uses ".cliversion"; remove the old file.

DotnetCLIVersion.txt still being in the source tree is misleading and makes it harder to notice the new file.

@weshaggard @chcosta

### CODE REVIEW

**Comment by chcosta** [comment]
It looks like there are a couple of places where DotNetCliVersion.txt will need to be converted to use .cliversion for repo's that consume buildtools (ie in CloudTestTasks and PerfTesting.targets), but none of those instances should affect building the BuildTools repo itself.

**Comment by dagood** [comment]
Ah, interesting... will that make converting product repos to use bootstrap.ps1 a "synchronized"/breaking buildtools change, then?

**Comment by chcosta** [comment]
Yes.

@weshaggard , in general is the intention to make these breaking changes in BuildTools and force repo's to conform when updating their BuildTools version, or to support both init-tools and bootstrapping behaviors in BuildTools so that repo's can consume other changes while transitioning to use the bootstrapping?

**Comment by weshaggard** [comment]
>@weshaggard , in general is the intention to make these breaking changes in BuildTools and force repo's to conform when updating their BuildTools version, or to support both init-tools and bootstrapping behaviors in BuildTools so that repo's can consume other changes while transitioning to use the bootstrapping?

We should try to make them opt-in and phase them out over time. In other words I would suggest we update targets to support both for a while. Can you point me at what is actually reading the DotNetCliVersion.txt file directly? It was never intended to be consumed by anything but the bootstrapping scripts.

**Comment by Chrisboh** [comment]
@dagood can you merge or close this?

**Pull request merged**
