### PR TITLE
Remove reference to old dumpling URL

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
The host __dumpling.int-dot.net__ has been decommissioned for a while. This updates the dumpling helper scripts to remove references to the old host.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
Maybe we just get rid of this entire file? I can't imagine it is still getting used.

**Review by DrewScoggins — APPROVED** [review]
LGTM

**Comment by GrabYourPitchforks** [comment]
Thanks for the check. :)

**Comment by GrabYourPitchforks** [comment]
Bah, that was supposed to be a squash merge.

**Pull request merged**
