### PR TITLE
Update build tools version to 1.0.26-prerelease-00620-01

### PR DESCRIPTION
**Pull request by maririos**
Update to get the latest changes of the Run Command Tool.

cc: @joperezr 
FYI: @Priya91 @tyoverby

### CODE REVIEW

**Comment by crummel** [comment]
Build finished.

**Comment by joperezr** [comment]
LGTM

**Comment by maririos** [comment]
Hi @crummel, What does that mean? Was it green?

**Comment by crummel** [comment]
Sorry Mariana, I had a Jenkins plugin go rogue on me and start builds on a bunch of pull requests.  I fixed it now.

**Comment by maririos** [comment]
Today there was a fix to the Run Command Tool, so I'm going to close this PR and open another one with a more updated version of BT.
Thanks!

**Pull request closed without merging**
