### PR TITLE
Set test errorlevel for uap correctly

### PR DESCRIPTION
**Pull request by ViktorHofer**
Relates to https://github.com/dotnet/corefx/issues/32452

### CODE REVIEW

**Comment by safern** [comment]
I meant to comment not to approve :smile: -- but yes I wonder why  this is needed if we already check for the failed result.

**Comment by ViktorHofer** [comment]
The code you linked is only responsible for the output. The error level was always 0 as the uninstall command of the WindowsStoreAppLauncher was used and therefore %ERRORLEVEL% was wrong, which we used in the template to output the error level. I believe CI uses this for the retry detection (see issue linked at the top).

**Comment by ViktorHofer** [comment]
We can probably get rid of the parsing and instead just check the ERRORCOUNT here too.

**Comment by safern** [comment]
Ah, I see, yes, what you're doing is for when we call RunTests.cmd manually (Helix) and not through the test.targets that capture the error from the output. 

So instead should we exit RunTests.cmd with an error? I.e `exit %ERRORLEVEL%` ??

**Comment by safern** [comment]
From this comment: https://github.com/dotnet/corefx/issues/32452#issuecomment-424853120

It looks to me like we should exit with error code instead.

**Comment by MattGal** [comment]
yeah I don't think this works as is unless you store off the error level into a different variable name and then exit with it... since I believe putting `exit %ERRORLEVEL%` at the end would end up exiting still with the errorlevel from the move command.

If you want to go this route, I'd suggest we store errorlevel into something like "APPX_ERRORLEVEL" and exit with its value

**Comment by safern** [comment]
I see that in RunTests.cmd we do exit with %ERRORLEVEL% `EXIT /B %ERRORLEVEL%` -- but I agree with @MattGal that the move command might override the variable.

**Comment by ViktorHofer** [comment]
Using %ERRORCODE% is fine here as it's special cased in cmd scripts and means either the value of the environment variable with that name and if none set it uses the ERRORCODE command.

blogs.msdn.microsoft.com/oldnewthing/20080926-00/?p=20743

**Comment by MattGal** [comment]
@ViktorHofer I assume you mean ERRORLEVEL not ERRORCODE, but yes while it works the way that article describes, it often leads to confusion.  Your call if you want that :)

**Comment by ViktorHofer** [comment]
> @ViktorHofer I assume you mean ERRORLEVEL not ERRORCODE

yeah sorry for the confusion. replied from my mobile phone.

> I still think it should have a special name but this works.

This was a least effort change :) I agree that it could cause confusion, at least the comment should help. Let's keep it like that for now.

**Pull request merged**
