### PR TITLE
[release/2.1] Merge master into release/2.1 in preparation for preview2 builds

### PR DESCRIPTION
**Pull request by dagood**
This merge includes the change to produce preview2 packages. Merge https://github.com/dotnet/buildtools/pull/1963 first so that `master` produces preview3 packages and doesn't collide.

### CODE REVIEW

**Comment by eerhardt** [comment]
Was this a clean merge?  Or did you have to resolve anything?

**Comment by dagood** [comment]
Not completely clean, here's the list of files with conflicts:

```
src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/FetchOrchestratedBuildManifestInfo.cs
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
src/Microsoft.DotNet.VersionTools/BuildManifest/Model/PackageArtifactModel.cs
src/nuget/Microsoft.DotNet.VersionTools.nuspec
src/packages.builds
```

They all had easy resolutions:

 * Most were where we ported something to `release/2.1`, and then made more changes around the same lines in `master`.
 * One special case was the conflict between changing prerelease to preview2 in `master`, and changing prerelease to preview1 in `release/2.1`. (Ideally we would have forked `release/2.1` after `master` was already building preview1, and we wouldn't have this conflict.)

After resolving them, I ended up with my commit looking exactly like the `master` commit I merged from, which is what I'd expect because we didn't have any release/2.1-specific hotfixes.

**Comment by weshaggard** [comment]
Oops I missed that you had opened this. I already merged https://github.com/dotnet/buildtools/pull/1965.

**Comment by weshaggard** [comment]
I saw similar conflicts and resolved them by taking master.

**Pull request closed without merging**
