### PR TITLE
Add vim swp files to git ignore.

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by alexperovich** [comment]
@weshaggard Are there any other temporary file types I should add to this while I'm working on it?

**Comment by bartonjs** [comment]
https://github.com/dotnet/corefx/pull/557/files shows the version of this change from corefx (includes more variants of the swp file)

**Comment by alexperovich** [comment]
Updated and squashed.

**Comment by bartonjs** [comment]
LGTM

**Pull request merged**
