### PR TITLE
Add Feed props file, alleviate taskdir property conflict 

### PR DESCRIPTION
**Pull request by chcosta**
Addresses https://github.com/dotnet/core-eng/issues/2439

### CODE REVIEW

**Comment by chcosta** [comment]
@jcagme , I'm pretty sure this change will break some people (like @johnbeisner) who appear to be directly importing the targets file (https://github.com/dotnet/cli/blob/632e9e762b4c7f04339759903b33fe4985e6e882/build/Publish.targets#L3).  Are you aware of anywhere else that the targets file is being explicitly imported?

I don't know if anyone else is explicitly importing the targets file rather than relying on automatic imports.  @johnbeisner, do you have concerns with this change?  I suppose that you could continue to be explicit and import both the props and targets files when you update to a version of the package which includes this split.

**Comment by jcagme** [comment]
Not to be honest since it seems that there were changes on the config files from the creation of this to now.  I think just @johnbeisner

Probably @mmitche has a better idea on who else might be hit?

**Comment by johnbeisner** [comment]
@chcosta 
To be clear, there is no action on CLI until CLI moves the 'BuildToolsFeed' version forward; correct?

**Comment by mmitche** [comment]
Most places are importing the targets file.  Most of the repositories in orchestrated build.  Many of these places are only using the feed tasks package.

So what does this mean?  Line to import the targets file will just need to be removed?  e.g. https://github.com/Microsoft/visualfsharp/blob/master/PublishToBlob.proj#L16

**Comment by chcosta** [comment]
If they're not importing as a PackageReference, then a line importing the props file will need to be added

```
  <Import Project="$(MSBuildThisFileDirectory)packages\$(FeedTasksPackage).$(FeedTasksPackageVersion)\build\$(FeedTasksPackage).props" />
  <Import Project="$(MSBuildThisFileDirectory)packages\$(FeedTasksPackage).$(FeedTasksPackageVersion)\build\$(FeedTasksPackage).targets" />
```

**Comment by chcosta** [comment]
I suppose we could continue to live with everything in the targets file.  I'm curious to know how many repos are following the direct import pattern though.

**Comment by mmitche** [comment]
@chcosta 10 maybe? We can certainly change it.

**Comment by chcosta** [comment]
I think it's reasonable to stay with the single targets file rather than a props + targets file.  There are two reasons I can think of to change it though.

**1. Support task usage for non-csproj / vbproj projects**

Projects using MSBuild 15.0+ which utilize PackageReference auto-imports.  Even more than that, it's only really applicable to non csproj or vbproj projects because non csproj / vbproj projects won't auto-import the targets but they will auto-import the props.  That only means that someone could directly utilize the tasks from this package and bypass the targets.  I don't think that's a really strong scenario or something we need to support.  If someone is using a PackageReference in a ".proj" file (for instance), they could use the same import functionality by adding a line like this...

```
  <!-- Only csproj or vbproj files auto-import the target extensions, so explicitly import these files -->
  <Import Project="$(MSBuildProjectExtensionsPath)$(MSBuildProjectFile).*.targets" Condition="Exists('$(MSBuildProjectExtensionsPath)')" />
```

**2. Follow standard MSBuild conventions**

If we want to establish a convention for buildtools packages which align closer with typical MSBuild / Nupkg conventions, then the fundamental change would be to additionally move this section from the targets file into the props file...

```
  <PropertyGroup>
    <PushToBlobFeed_Overwrite Condition="'$(PushToBlobFeed_Overwrite)' == ''">false</PushToBlobFeed_Overwrite>
    <PushToBlobFeed_MaxClients Condition="'$(PushToBlobFeed_MaxClients)' == ''">8</PushToBlobFeed_MaxClients>
    <FileRelativePathBase Condition="'$(FileRelativePathBase)' == ''">assets</FileRelativePathBase>
    <FileRelativePathBase Condition="!HasTrailingSlash('$(FileRelativePathBase)')">$(FileRelativePathBase)/</FileRelativePathBase>
    <ManifestName Condition="'$(ManifestName)' == ''">$(GitHubRepositoryName)</ManifestName>
  </PropertyGroup>
```

...but remove the Conditions...

```
  <PropertyGroup>
    <PushToBlobFeed_Overwrite>false</PushToBlobFeed_Overwrite>
    <PushToBlobFeed_MaxClients>8</PushToBlobFeed_MaxClients>
    <FileRelativePathBase>assets/</FileRelativePathBase>
    <ManifestName>$(GitHubRepositoryName)</ManifestName>
  </PropertyGroup>
```

This would be a more typical pattern with props being imported and processed first, then the project file being processed (allowing the user to override those values), then targets being imported.

**Comment by chcosta** [comment]
@johnbeisner , that's correct, there would be no action needed from any repo until they move to consume to a newer version of the feed package.

**Comment by weshaggard** [comment]
Sorry I'm a little late to the party but I don't see enough value to split this into a props and a targets file I would just keep everything in the targets file.

**Pull request merged**
