### PR TITLE
Add task to get the resources and merge them into the common pri for …

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
…external dependencies (#1630)

* Add task to get the resources and merge them into the common pri for external dependencies

* PR Feedback

* PR Feedback, remove System.Windows.Forms dependency, and change target Outputs

* Make RewResourceWriter IDisposable

* Fix assembly filtering when it doesn't need resources to be extracted

* Change to NS implementation using MetadataReader instead of Assembly.LoadFrom

* Add option to disable external resources extraction and use runner's default pri file if common pri doesn't exist

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
I don't have permissions to add reviewers. @safern could you review and add folks as necessary?

This fixes #1954 

I built buildtools locally with this change and used it with our WCF uwp6.0 and uwp6.1 branches and verified that it fixes the problem.

**Comment by safern** [comment]
Thanks @StephenBonikowsky for porting this. I've added @tarekgh and @MattGal

**Comment by safern** [comment]
You need to port https://github.com/dotnet/buildtools/commit/bbbede8fef122f43180b343ca93d1032904a6cb7 and https://github.com/dotnet/buildtools/commit/1f57d19b4a19c972d7e94050cd839a4b992f39fc as well because these commits where done specifically for WCF and they impact the resource extractor.

**Comment by StephenBonikowsky** [comment]
Ok, will add them.

**Pull request merged**
