### PR TITLE
Allow custom attributes in build manifest 'BuildIdentity'

### PR DESCRIPTION
**Pull request by dagood**
Also improve the required attribute mechanism to avoid redundant writes and verify dictionary contents during ToXml.

Core-Setup and CLI will use this to pass `ProductVersion` to the Copy to Latest post-build step (https://github.com/dotnet/buildtools/pull/1871). The repos need to take this change and add `ManifestBuildData="ProductVersion=$(...)"` on `PushToBlobFeed`.

I made `FetchOrchestratedBuildManifestInfo` put the extra info in MSBuild items so I can use it during final publish steps.

ASP.NET Core should pass this too: with all three repos, we can remove some code that derives product version from the blob artifact paths for README generation: https://github.com/dotnet/buildtools/pull/1876#discussion_r164016705, https://github.com/dotnet/buildtools/pull/1881. (I couldn't wait for this data to flow to get the READMEs generating. Copy to Latest is less time-sensitive.)

/cc @johnbeisner @natemcmaster

### CODE REVIEW

**Comment by natemcmaster** [comment]
> ASP.NET Core should pass this too:

You lost me here. What changes do we need to make?

**Comment by dagood** [comment]
Sorry, that's referring to:

> The repos need to take this change and add `ManifestBuildData="ProductVersion=$(...)"` on `PushToBlobFeed`.

It was `2.1.0-preview1-28181` for the last aspnet release/2.1 build, don't know which prop that is.

/cc @pranavkm

**Comment by natemcmaster** [comment]
@dagood thanks. Looks like a simple change on our end

**Comment by dagood** [comment]
@mmitche It's actually even more specific: only repos that need to have their blob assets copied to a "latest" virtual dir in the `dotnetcli`/`dotnetclichecksums` storage accounts. Only Core-Setup, CLI, and ASP.NET will be doing this.

Other repos may pass in ProductVersion to show up on the generated README.md, regardless what they produce, but there's generally no need since packages/blobs are self-descriptive.

**Pull request merged**
