### PR TITLE
Force explicit qualifier usage of required parameter in GenAPI

### PR DESCRIPTION
**Pull request by mellinoe**
CommandLineParser chokes on unix-style paths for positional parameters.

@Priya91 , @ericstj 

After this fix is published to NuGet, we need to update the version grabbed by the tool runtime, and update notsupported.targets slightly (to pass this qualifier).

### CODE REVIEW

**Comment by mellinoe** [comment]
I manually verified that this fixes the corefx build issues.

**Comment by dagood** [comment]
I don't know GenAPI, but the plan sounds good to me. Thanks!

**Comment by mellinoe** [comment]
@ericstj I changed GenAPI.targets as well. Is anyone consuming that nuget package currently?

**Comment by Priya91** [comment]
Thanks @mellinoe

**Pull request merged**
