### PR TITLE
Update build tools to latest version.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Replace back-tick char with single-quote char.
Add missing closing parenthesis.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test this please

**Comment by jhendrixMSFT** [comment]
@ericstj FYI some clean-up in resolveContract.targets.

**Comment by joperezr** [comment]
LGTM

**Comment by ericstj** [comment]
Yikes, thanks for catching this.

**Pull request merged**
