### PR TITLE
Fix paths coverage and report tools

### PR DESCRIPTION
**Pull request by mmitche**
/cc @stephentoub @AlfredoMS 

@ericstj I think this is related to your build tools updates.  Can you take a look?

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM. Thanks for fixing it.

**Comment by ericstj** [comment]
Ah, indeed nuget v3 changes the package cache structure.  I did fix the cases of this that I knew about in System.IO.Compression but was unaware that it was happening here as well.  Long term it might make sense to ask nuget to resolve these paths for you and avoid the hardcoding.

**Comment by mmitche** [comment]
@ericstj How much work is involved in that or can you point me to an example?

**Comment by ericstj** [comment]
@mmitche have a look at what @mellinoe is doing for partial facades in FindPartialFacadeContractReference. https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets

**Pull request merged**
