### PR TITLE
Xunit runner for perf in helix

### PR DESCRIPTION
**Pull request by dsgouda**
Xunit runner script to perform perf specific jobs on helix
@ChadNedzlek @MattGal @Chrisboh @davmason @brianrob @karajas

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Most of this is just copied from the existing xunitrunner.py. Any particularly interesting comments I would have have to do with the parts copied from there (the perf specific parts are mostly pretty straightforward).  Since we intend to merge those two together, there is no sense fixing them here without fixing them in the source location first, so this is fine to unblock the perf team.

**Comment by ChadNedzlek** [comment]
You'll need to squash the commits before I can sign-off (since squashing will invalidate my sign-off)

**Comment by dsgouda** [comment]
@dotnet-bot Test this please.

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@ChadNedzlek the commits are squashed now

**Pull request merged**
