### PR TITLE
Resolve NuGet packages from packages folder without using temp cache

### LINKED ISSUE #117: ResolveNuGetPackages causes unbounded growth of NuGet cache
While working on #116, I kept running out of disk space: I would free some up, but then just a few minutes later the drive would be full again. I discovered that a full build of CoreFX is adding over half a gig to the NuGet cache (%TEMP%\nuget), even with no changes and nothing new to download. I narrowed this down to the ResolveNuGetPackages task: something about this task is causing new packages to appear in the cache, even when they should already be there.

### PR DESCRIPTION
**Pull request by eatdrinksleepcode**
Fixes #117 

OptimizedZipPackage extracts packages to %TEMP%\nuget in order to access the files; however, installing the packages already extracts them to the local packages directory. Using SharedPackageRepository uses the packages in their already extracted locations, eliminating the need for the cache.

### CODE REVIEW

**Comment by akoeplinger** [comment]
I just tried it and my nuget temp folder is clean, thanks :+1:

**Comment by weshaggard** [comment]
Thanks for having a look at fixing this. I will take a closer look and try this out later today.

**Comment by weshaggard** [comment]
LGTM thanks @eatdrinksleepcode for fixing this.

**Comment by eatdrinksleepcode** [comment]
Happy to save everyone a few extra bits :)

By the way, I have not to my knowledge signed the contributor agreement, and was expecting a friendly greeting from dotnet-bot inviting me to do so. Does he not watch this repo?

**Comment by Petermarcu** [comment]
@eatdrinksleepcode , thanks for the heads up on the CLA from the dotnet-bot. That should be fixed now.

**Pull request merged**
