### PR TITLE
Create Build.Common.targets that is the one import to rule them all.

### PR DESCRIPTION
**Pull request by weshaggard**
This change adds a Build.Common.targets that will be imported by
individual repo dir.targets files to get all the individual project
targets needed. It pulls back in a lot of the changes that have
been made directly in corefx repo dir.targets and makes them more
generalized for other repo's to consume the same functionality.

The basic idea is to try and minimize the boot strapping code and
eliminate duplication for all the repos that will be using
the build tools package.

For an example of what the changes in corefx will look like once we update to using this see my forked update https://github.com/weshaggard/corefx/commit/8f9d375f0572f336d06e3a3fc1282e76789fe1f8.

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @nguerrera @FiveTimesTheFun @mmitche

**Comment by mmitche** [comment]
This looks great.  Are you going to push to import this in the other repos?

**Comment by weshaggard** [comment]
@mmitche Yes that is the plan, any .NET Core based repo that is using buildtools should be importing this.

**Comment by nguerrera** [comment]
LGTM. Thanks for doing this. :)

**Comment by FiveTimesTheFun** [comment]
Great!  Thank you, having a look now.

**Comment by weshaggard** [comment]
I pulled in the last couple of changes by @krwq  and @stephentoub as part of this and now I'm submitting this change. Note I will follow-up this will a buildtools update tomorrow for corefx so please no one else try to update the buildtools version in corefx until then.

**Pull request merged**
