### PR TITLE
Add infrastructure for building packages

### PR DESCRIPTION
**Pull request by ericstj**
Work is still ongoing but this enables the majority of the packaging infrastructure.

You can see consumption here: 
https://github.com/ericstj/corefx/compare/master...ericstj:packaging

Still left before merge:
- [x] Eliminate nuproj dependency
- [x] Investigate diffs with current TFS build
- [x] Enable more corefx packages
- [x] Clean up history

Post merge:
- [ ] Enable build of nuspecs using coreCLR (requires NuGet API)
- [ ] Pack nuspecs
- [ ] Integrate with @weshaggard's build refactoring
- [ ] Docs

### CODE REVIEW

**Comment by ericstj** [comment]
Diffs with TFS were due to nuget dropping folders that start with '.' (like .NETFramework,Version=v4.5).  Fixed this by passing `-NoDefaultExcludes`.  I've also cleaned up the history a bit.

**Comment by ericstj** [comment]
Ok, I think this is ready now.

**Comment by weshaggard** [comment]
LGTM. Please file an issue for the post merge list.

**Comment by ericstj** [comment]
Thanks!

**Comment by andschwa** [comment]
This is going to be awesome! I would love to build NuGet packages on Linux.

**Pull request merged**
