### PR TITLE
Enable running tests in our CI builds

### PR DESCRIPTION
**Pull request by maririos**
Our CI was building the Build Tools repo without running the tests.
Now that we have test to run, we want to build and run them.

cc: @joperezr @karajas @mmitche

### CODE REVIEW

**Comment by mmitche** [comment]
LGTM, merge away (assuming they pass at the moment)

**Comment by joperezr** [comment]
LGTM

**Comment by joperezr** [comment]
@dotnet-bot test ci

**Comment by joperezr** [comment]
@dotnet-bot test ci please

**Pull request merged**
