### PR TITLE
Update MSBuild package references

### PR DESCRIPTION
**Pull request by joperezr**
Updating MSBuild packages

fixes: #574 

cc: @weshaggard 
FYI: @stephentoub @dsplaisted

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks!!

**Comment by joperezr** [comment]
Merging this for now to fix package restore warning when running init-tools. I'll address any feedback on my next PR.

**Comment by weshaggard** [comment]
Do you know if this fixes the warnings?

```
D:\git\corefx\packages\Microsoft.DotNet.BuildTools\1.0.25-prerelease-00220\lib\tool-runtime\project.json(37,37):
warning NU1012: Dependency conflict. Microsoft.Build 0.1.0-preview-00017 expected System.Diagnostics.Contracts >=
 4.0.1-rc2-23712 but got 4.0.0
D:\git\corefx\packages\Microsoft.DotNet.BuildTools\1.0.25-prerelease-00220\lib\tool-runtime\project.json(37,37):
warning NU1012: Dependency conflict. Microsoft.NETCore.Console 1.0.0-rc2-23923 expected System.Diagnostics.Contra
cts >= 4.0.1-rc2-23923 but got 4.0.0
Done initializing tools.
```

**Comment by joperezr** [comment]
@weshaggard it does :)

**Pull request merged**
