### PR TITLE
Remove nuget core

### PR DESCRIPTION
**Pull request by ericstj**
This removes our dependency on nuget.core so that we can run the packaging tasks on CoreFx.

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot please test Windows Debug

**Comment by joperezr** [comment]
LGTM, Also I've tested this in .Net Core MSBuild and it works as expected.

**Comment by mellinoe** [comment]
LGTM

**Comment by ericstj** [comment]
Thanks!

**Pull request merged**
