### PR TITLE
Update xunit.runner.dependencies.netcore depend.. to v1.0.1-prerelease

### PR DESCRIPTION
**Pull request by FiveTimesTheFun**
Includes commit df2ffbbd.. from stephentoub
https://github.com/FiveTimesTheFun/xunit/commit/df2ffbbdf736bc0855ac68d0aec4235f975f484e

"Change how Task is created in XunitWorkerThread"

### CODE REVIEW

**Comment by stephentoub** [comment]
For reference, this significantly reduces the startup time for a bunch of tests... on my machine, tests that previously took ~2 seconds now take ~0.2 seconds.

**Comment by weshaggard** [comment]
LGTM @FiveTimesTheFun how/where are you currently building xunit.runner.dependencies.netcore package?

**Comment by stephentoub** [comment]
LGTM

**Comment by FiveTimesTheFun** [comment]
@weshaggard  - the sources and nuspec are in https://github.com/FiveTimesTheFun/xunit/tree/netcore/src - I want to bring that upstream to xunit.

**Pull request merged**
