### PR TITLE
Update roslyn version to latest available (2.8.0-beta4-62810-06)

### PR DESCRIPTION
**Pull request by ahsonkhan**
See https://github.com/dotnet/corefx/pull/29003#issuecomment-380290429

cc: @joperezr, @weshaggard, @VSadov

### CODE REVIEW

**Comment by joperezr** [comment]
How stable is this version? We usually try to only use builds comming from the release branch

**Comment by joperezr** [comment]
Did you push the package and its dependencies to the buildtools feed? If not then build will fail

**Comment by joperezr** [comment]
Did you try building corefx with this compiler?

**Comment by ahsonkhan** [comment]
> Did you push the package and its dependencies to the buildtools feed? If not then build will fail

No. I was trying to figure out how to dogfood the build locally to test this. Any docs available that I can read to figure out how to test this change?

> Did you try building corefx with this compiler?

Not yet.

**Comment by VSadov** [comment]
This package is from the release branch for 15.7.x

At this point it would be pretty bad if it does not build CoreFX

**Comment by VSadov** [comment]
It is worth trying though before merging.

**Comment by joperezr** [comment]
No docs yet, I can help you uploading the packages tomorrow. Definitely try building corefx and coreclr with this compiler before merging since and auto PR will be generated for it and we don’t want to block buildtools ingestion

**Comment by ahsonkhan** [comment]
> Definitely try building corefx and coreclr with this compiler before merging since and auto PR will be generated for it and we don’t want to block buildtools ingestion

How can I build those locally using the local build of buildtools? What exactly do I need to drop/replace to test this?

**Comment by joperezr** [comment]
For these type of changes, easiest is to just 
 - run init-tools.cmd
 - delete Tools directory manually
 - apply your same changes on folder packages\microsoft.dotnet.buildtools\<latestVersion>\lib\...
 - run init-tools.cmd again

**Comment by ahsonkhan** [comment]
I tried those steps, but I end up getting a different compiler version (2.8.0) instead of 2.8.0-beta4-62810-06.
> D:\GitHub\Fork\corefx\Tools\microsoft.net.compilers\2.8.0

Coreclr built successfully (with 2.8.0).

However, corefx didn't.
> D:\GitHub\Fork\corefx\Tools\Microsoft.CSharp.Core.targets(106,11): error MSB4064: The "OverrideToolHost" parameter is n
ot supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
 [D:\GitHub\Fork\corefx\src\System.Memory\ref\System.Memory.csproj]
D:\GitHub\Fork\corefx\Tools\Microsoft.CSharp.Core.targets(67,5): error MSB4063: The "Csc" task could not be initialized
 with its input parameters.  [D:\GitHub\Fork\corefx\src\System.Memory\ref\System.Memory.csproj]
D:\GitHub\Fork\corefx\Tools\Microsoft.CSharp.Core.targets(106,11): error MSB4064: The "OverrideToolHost" parameter is n
ot supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
 [D:\GitHub\Fork\corefx\src\System.Threading.Tasks.Extensions\ref\System.Threading.Tasks.Extensions.csproj]
D:\GitHub\Fork\corefx\Tools\Microsoft.CSharp.Core.targets(67,5): error MSB4063: The "Csc" task could not be initialized
 with its input parameters.  [D:\GitHub\Fork\corefx\src\System.Threading.Tasks.Extensions\ref\System.Threading.Tasks.Ex
tensions.csproj]

**Comment by joperezr** [comment]
That is because you most likely didn’t push the roslyn packages to the buildtools feed. I bet that if you check the init-tools log there is a warning about not finding the package. In order to workaround that hou would have to add the roslyn feed to the restore command on the init-tools.cmd inside the buildtools package.

**Comment by ahsonkhan** [comment]
> In order to workaround that hou would have to add the roslyn feed to the restore command on the init-tools.cmd inside the buildtools package.

Both repos (corefx/coreclr) built successfully, locally (on Windows).

**Comment by joperezr** [comment]
Yes, or else ingestion would fail.

**Comment by weshaggard** [comment]
We should proceed with caution when updating to a newer compiler during this last week of the release. Please be sure we get good test coverage. 

cc @joshfree

**Comment by joperezr** [comment]
This is not on the release branch though, so that should in theory not be a problem unless we have another merge from master planned, right?

**Comment by weshaggard** [comment]
>This is not on the release branch though, so that should in theory not be a problem unless we have another merge from master planned, right?

There is another merge planned for RC happening this friday.

**Comment by ahsonkhan** [comment]
Given we plan to stick with C# 7.2 features, this compiler update isn't necessary yet. Thanks for the feedback!

**Comment by jkotas** [comment]
Now that master is open for 2.2, should we reopen this? @ahsonkhan I can take care of it if you do not have cycles.

**Comment by ahsonkhan** [comment]
> I can take care of it if you do not have cycles.

That would be great. Ty!

**Pull request closed without merging**
