### PR TITLE
Update desktop dependencies to support new test project.json and remove runtime.json from TestSuite.

### PR DESCRIPTION
**Pull request by karajas**
Remove runtime.json as tests now use a single project.json.

/cc @MattGal

### CODE REVIEW

**Comment by MattGal** [comment]
Change LGTM, testing now.

**Comment by MattGal** [comment]
Fails to build: D:\GIT\buildtools\src\Microsoft.DotNet.Build.Tasks\PackageFiles\packages.targets(25,5): error : Error when creating nuget lib package from D:\GIT\buildtools\src\nuget\Microsoft.DotNet.BuildTools.TestSuite.nuspec. System.IO.FileNotFoundException: File not found: 'Microsoft.DotNet.BuildTools.TestSuite\runtime.json'. [D:\GIT\buildtools\src\packages.builds]

**Comment by MattGal** [comment]
Need to remove this line to fix build: https://github.com/karajas/buildtools/blob/0c63833cabc901edecadb16ca25ee93059bbe360/src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec#L32

**Comment by karajas** [comment]
This was fixed in a previous PR

**Pull request closed without merging**
