### PR TITLE
Adding new versioning scheme to buildtools

### PR DESCRIPTION
**Pull request by joperezr**
Updating Buildtools and using the new versioning scheme.

cc: @weshaggard @ericstj 

FYI: @jhendrixMSFT

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM

What build number does this next package generate? Is it higher then 221?

**Comment by joperezr** [comment]
@weshaggard FYI: I have modified the build definition to pass in the revision number as the build number minor, for now it will be a no-op, but once this code gets merged then it will be used.

**Comment by joperezr** [comment]
> What build number does this next package generate? Is it higher then 221?

It generates 002 + the two digit day of the month. Today it would generate 00224 which is higher

**Comment by weshaggard** [comment]
So once this merges then (assuming no more commits past today) it will generate "000224-00" as the next build tools version number?

**Comment by joperezr** [comment]
Yes

**Comment by weshaggard** [comment]
What bout the checked in buildvalue.props file? Doesn't that need to be deleted and the targets that generate it removed?

**Comment by joperezr** [comment]
Talked offline with @weshaggard, the decision was to only remove the import of buildvalue.props file, We will cleanup the generation of it in a different PR

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
Looks like CI has been timing out on package restore since yesterday, this is not related to my change since other PR's are hitting this as well.

**Pull request merged**
