### PR TITLE
Update package dependencies.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Update package dependencies to the latest bits from dotnet-core.
Update perf tools package to latest build (the previously referenced
package no longer exists).

### CODE REVIEW

**Comment by mellinoe** [comment]
Where did the version of buildtools you are referencing here come from (1.0.25-prerelease-00065) ? The repo is still at build number 64.

**Comment by mellinoe** [comment]
For some reason the desktop build of GenFacades seems to still be pulling in an old version of a few packages. Strange.

**Comment by jhendrixMSFT** [comment]
This is a private build I produced in order to break out of a "chicken-and-egg problem", i.e. build tools depending on an older build of build tools that has missing nuget packages.

**Comment by jhendrixMSFT** [comment]
This build error is unique to building with VS 2013, I don't see it with VS 2015.

**Comment by jhendrixMSFT** [comment]
CC @ericstj

**Pull request closed without merging**
