### PR TITLE
Move Packages.zip to be a Supplemental Payload

### PR DESCRIPTION
**Pull request by MattGal**
Addresses https://github.com/dotnet/core-eng/issues/346
Ensures we don't force all users to create a Packages.zip

@chcosta , @wtgodbe 

Will need a separate PR for corefx if we want to adopt it there (may not be necessary)

Weird diff is from fixing XML formatting on CloudTest.targets;  I can undo this if you really want, otherwise please just use a diff tool that can ignore whitespace.

### CODE REVIEW

**Comment by wtgodbe** [comment]
Looks like the diff got confused & is basically showing you deleted, then re-inserted the majority of CloudTest.targets - can you point to where the actual changes are?

**Comment by MattGal** [comment]
@wtgodbe I don't know how to do this on github, but if you check out the branch in most visual Git tools you can ignore whitespace diffs.   I can alternately just make this two commits, just not immediately.

**Comment by MattGal** [comment]
@wtgodbe I undid my whitespace fixups.  Note that we plan to refactor CloudTest.targets in the near future as what's here currently is fairly messy.

**Comment by wtgodbe** [comment]
LGTM

**Pull request merged**
