### PR TITLE
Shift signing to avoid collision with IntelliSense build

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Intellisense hits the Compile target directly-- pushing the signing to before deployment to the output directory avoids colliding with it.

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @nguerrera @jhendrixMSFT 
@JeremyKuhne could you squash these commits?

**Comment by akoeplinger** [comment]
FYI I changed this to the Compile target in https://github.com/dotnet/buildtools/pull/39 to make it work on Mono/xbuild. PrepareForRun works there as well, so this is fine from my part :)

**Comment by JeremyKuhne** [comment]
Ugh- I can't seem to figure out how to rebase correctly. Working on it.

**Comment by JeremyKuhne** [comment]
Whatever I did to my master is making this nearly impossible for a git newbie. I've gotten to the point where I'm better off recreating this from scratch.  I'll have to spend some more quality time experimenting with rebasing.

**Pull request closed without merging**
