### PR TITLE
Remove perf tools prototype.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
The perf tools prototype is no longer required as we're moving to an
xunit based solution.

This will fix https://github.com/dotnet/buildtools/issues/253

### CODE REVIEW

**Comment by mellinoe** [comment]
LGTM

**Comment by ianhays** [comment]
Uhh, this also deleted the new xunit perf targets that enable us to run msbuild /p:performance=true within CoreFX. Was that intended?

**Comment by jhendrixMSFT** [comment]
Ah I didn't realize it had been repurposed.  I will restore it shortly.

**Comment by ianhays** [comment]
Could you also include the changes made in https://github.com/dotnet/buildtools/pull/270 to that restoration?

**Comment by jhendrixMSFT** [comment]
Yes I'll add them to the change.

**Pull request merged**
