### PR TITLE
Downgrade to NuGet 3.4.0-beta

### PR DESCRIPTION
**Pull request by ericstj**
A stable build of NuGet 3.4 was mistakenly
published to myget and we picked it up.

Undo that and depend on the pre-release
version.

/cc @anurse @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
I've mirrored the 3.4.0-beta-288 build to https://www.myget.org/F/dotnet-buildtools. I will unlist the 3.4.0 version, then delete it after we've upgraded every buildtools consumer.

**Comment by anurse** [comment]
Looks right to me

**Comment by ericstj** [comment]
Looks like a breaking API change, interesting that didn't show up in my local build (incremental fail perhaps?).  Will react to the breaking change...

**Comment by ericstj** [comment]
Ok, I unlisted the 3.4.0 versions.

**Pull request merged**
