### PR TITLE
Copy S.P.Corelib to S.P.Corelib.ni.dll to ensure the UAP F5 tests con…

### PR DESCRIPTION
**Pull request by AlexGhiondea**
…tinue to work

/cc @gkhanna79 @weshaggard @joperezr

### CODE REVIEW

**Comment by joperezr** [comment]
didn't you say that all that was required was for an empty file to be there? if so I think it would be better to have an echo command

**Comment by joperezr** [comment]
Also one more thing, can we log an issue to track the work of reverting this once we fix the runner properly?

**Comment by AlexGhiondea** [comment]
Simply echoing the file is not enough. It is better to just copy this over. We can have an issue tracking the removal of this -- not sure the right repo for it... probably still here.

**Comment by weshaggard** [comment]
Do we have an issue tracking the host update as this will break in shipping scenarios as well now that we have removed the ni.

**Comment by gkhanna79** [comment]
Which shipping scenario will it break? 2.1 based uwp host will have the right change (file issue against me for it).


Thanks,
Gaurav
________________________________

**Comment by AlexGhiondea** [comment]
@gkhanna79 which repo should I file the issue in?

**Comment by gkhanna79** [comment]
@AlexGhiondea Please file it in Core-Setup for 2.1 milestone.

**Comment by gkhanna79** [comment]
@weshaggard Can you please comment on what shipping scenarios would break?

**Comment by weshaggard** [comment]
>@weshaggard Can you please comment on what shipping scenarios would break?

Right now just the F5 debug scenarios in UAP but we aren't supporting that in 2.0 so I think it is fine to support it in 2.1.

**Comment by gkhanna79** [comment]
Yes, those would be supported for 2.1 and https://github.com/dotnet/core-setup/pull/2115 would account for the host update for the same.

**Pull request merged**
