### PR TITLE
Remove superfluous MakeDir call

### PR DESCRIPTION
**Pull request by naamunds**
With https://github.com/dotnet/buildtools/commit/a85967b2aab1bbed12c2dcb523cba9f0d4e51c8b, the Error 
in GenerateAssemblyInfo was changed to occur when AssemblyInfoFileDir
does not exist.  However, in the case where AssemblyInfoFileDir is set
to "$(BaseIntermediateOutputPath)$(MSBuildProjectName)\", it is expected
to not exist, and is created by a MakeDir task later in the target.

This is causing the build to fail when using the BuildTools in corefx (see 
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_release_prtest/2428/console)

With the fix to https://github.com/dotnet/buildtools/issues/231, this file will probably be reverted
back to how it was before the _AssemblyInfo.cs changes made for loc,
meaning that the Error will look for the existence of
$(IntermediateOutputPath).

Until that fix, though, I think the right workaround is to remove the
Error.

@ericstj @jhendrixMSFT

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
I think this is no longer required.  In change 82e19ef a MakeDir task was added to unconditionally create the directory if it doesn't exist.

**Comment by naamunds** [comment]
> I think this is no longer required. In change  82e19ef  a MakeDir task was added to unconditionally create the directory if it doesn't exist.

@jhendrixMSFT I'm not sure I understand what you mean by this.  Are you agreeing with the code change in this pull request, but saying that the Error will not need to be added back later with the fix for #231?  I'm thinking that that the fix for #231 will entail removing the MakeDir task, along with the rest of the changes I made to versioning.targets.

**Comment by naamunds** [comment]
I'll squash this to one commit before submitting.

**Comment by jhendrixMSFT** [comment]
LGTM

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
