### PR TITLE
Update package version.

### LINKED ISSUE #566: Update packages and change desktop libs dependency to net45 from net46.
Refer [here](https://github.com/dotnet/buildtools/pull/564/files/580ed7ea9646b6684834a52c51d14062ecb30b76#r57099428)

### PR DESCRIPTION
**Pull request by Priya91**
cc @weshaggard @ericstj 

fixes #566

### CODE REVIEW

**Comment by weshaggard** [comment]
Lets keep BuildTools on RC2 builds for now can you update to use "rc2-23923" build.

**Comment by ericstj** [comment]
Also, can you update the nuspecs in the repo at the same time?

**Comment by Priya91** [comment]
@weshaggard @ericstj 
> Lets keep BuildTools on RC2 builds for now can you update to use "rc2-23923" build.

Done.

> Also, can you update the nuspecs in the repo at the same time?

Done.

**Comment by ericstj** [comment]
LGTM, you can add Regex to the nuspec for netcore.extensions like we discussed in f2f

**Pull request merged**
