### PR TITLE
Removing BuildValues.props and the targets that modify it.

### PR DESCRIPTION
**Pull request by joperezr**
We don't need this anymore with our new versioning scheme. I have already changed the internal build to not pass UpdateBuildValues anymore.

cc: @weshaggard @ericstj

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @jhendrixMSFT

**Comment by joperezr** [comment]
Ping

**Comment by weshaggard** [comment]
LGTM we should also consider cleaning out the supporting infrastructure (i.e. custom targets and tasks), that generates this.

**Comment by joperezr** [comment]
Was this repo the only buildtools consumer that uses the infrastructure, I left it in case there were others that were using revisions for their versioning, but I can remove that later if nobody uses it.

**Comment by weshaggard** [comment]
@jhendrixMSFT would have to say for sure but I believe it was the only repo using it.

**Pull request merged**
