### PR TITLE
Updated buildtools to use netcore 101

### PR DESCRIPTION
**Pull request by ianhays**
This should remove all references to older versions of xunit

@ellismg @weshaggard @mellinoe

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM

**Comment by ianhays** [comment]
CI failed with ```d:\j\workspace\dotnet_buildtools\innerloop_prtest\build.proj(24,5): error : Unable to locate xunit.console.netcore 1.0.2-prerelease-00101```

Local build passed fine. package 101 definitely exists. Merge anyways?

**Comment by ellismg** [comment]
@dotnet-bot test this please (package restore failed to find something on myget?)

**Comment by ellismg** [comment]
Thanks, @ianhays

**Comment by ianhays** [comment]
Thanks @ellismg. Kicked off (hopefully) the last build necessary to upgrade to xunit 2.1.0

**Comment by ianhays** [comment]
Build failed - couldnt find 101. Gonna kick it off again

**Comment by ianhays** [comment]
Hmm. Same error.

**Pull request merged**
