### PR TITLE
Bump xunit.console.netcore version (for Ctrl+F5 pause)

### PR DESCRIPTION
**Pull request by nguerrera**
This is needed so that I can upload a new package to myget to get -wait support, 
which in turn will allow me to wire things up so that Ctrl+F5 in VS actually pauses
after a test run.

### CODE REVIEW

**Comment by nguerrera** [comment]
cc: @weshaggard @stephentoub

**Comment by nguerrera** [comment]
Don't merge yet. Turns out there are other changes needed that I'm working through.

**Comment by ellismg** [comment]
LGTM.

**Comment by weshaggard** [comment]
@nguerrera The change looks good to me as well. Are you planning to upload the new packages?

**Comment by nguerrera** [comment]
@weshaggard Yes. On it.

**Pull request merged**
