### PR TITLE
Update baseline

### PR DESCRIPTION
**Pull request by ericstj**
/cc @bartonjs @saurabh500

### CODE REVIEW

**Comment by ericstj** [comment]
ping can someone please have a look today?  This needs to go in tonight's build.

**Comment by saurabh500** [comment]
@ericstj what is the role of this file.
I am curious about the implications of this change. 
The changes for Sql Client look good based on the version change.

**Comment by ericstj** [comment]
The purpose of this is to ensure that package dependencies we emit have a consistent version.  Prior to this change a package building in CoreFx that referenced SQL client would emit a dependency to a package version 4.0.0-... which wouldn't exist.  For SqlClient this is a noop because no other libraries in CoreFx/WCF actually depend on it.  It's more important for Crypto since we have dependencies in corefx today that are creating invalid package refs.

**Comment by saurabh500** [comment]
Thanks. For System.Data LGTM

**Pull request merged**
