### PR TITLE
Remove hard-coded repository for "git push" when updating build values.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Add property GitPushRemote that allows the repository to be specified
when pushing the commit of the automated build value change.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@weshaggard This should be the last change required to start using VSO vNext.

**Comment by mellinoe** [comment]
nit: Should we call it GitPushRemote? Looks like the git documentation actually calls this argument "Repository".

**Comment by jhendrixMSFT** [comment]
@mellinoe I like it, will push the change shortly.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
