### PR TITLE
Build log filename variable

### PR DESCRIPTION
**Pull request by jthelin-microsoft**
- Set name of build log file and build project file into env variable so
they are more easily discoverable in the log file, and only defined
once.
- Fix URL for .NET Developer Guide and minor typo in comments.

### CODE REVIEW

**Comment by weshaggard** [comment]
Thanks @jthelin-microsoft while the change looks good to me I'm curious what prompted you to make the env variable changes? How does this make them more discoverable in the log file? Don't you already need to know the log file to discover what is in it :)

**Comment by jthelin-microsoft** [comment]
If your build is running on a remote build server somewhere in the cloud, you will often see the contents of the build log (for example Jenkins-CI web page) without opening the log file directly. 

If [or more likely when!] you have to log in to the build server to diagnose a tricky build failure, it is very useful to be able to quickly find that log file and associated build artifacts on disk.

This is especially true if your build server handles multiple build definitions from multiple projects, all with very similar but subtly different directory path locations, like our internal tfs servers currently do.

**Comment by jthelin-microsoft** [comment]
And the "only defined once" bit is quite useful too ;)

**Comment by weshaggard** [comment]
More interesting to me is the actual build command line which we are also putting into the log which is why we call the build target twice once with echo and once without. However I'm also perfectly fine with having them be in environment variables assuming your CI system or logs are capturing those. As for the duplication it isn't really bad in this build.cmd it is a little worse in the build.cmd in our corefx repo so feel free to submit a PR with an update for that one as well (assuming you are doing work with that repo as well, which I assume you are otherwise I'm not sure why you are using our build tools :))

**Comment by jthelin-microsoft** [comment]
Yes, seeing the full exact command line that is being executed makes things so much easier too!

Equivalent change submitted to fxcore as well, as you suggested: https://github.com/dotnet/corefx/pull/762

**Pull request merged**
