### PR TITLE
Add retry logic when downloading the CLI from Azure blob storage.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Downloading from Azure can transiently fail for a number of reasons.  Add
some retry logic when downloading to avoid transient failures.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Here's the code in a non-compressed form.

$retryCount = 0;
$success = $false;
do
{
    try
    {
        (New-Object Net.WebClient).DownloadFile('%DOTNET_REMOTE_PATH%', '%DOTNET_LOCAL_PATH%');
        $success = $true;
    }
    catch
    {
        if ($retryCount -ge 6)
        {
            throw;
        }
        else
        {
            $retryCount++;
            Start-Sleep -Seconds (5 * $retryCount);
        }
    }
}
while ($success -eq $false);

**Comment by jhendrixMSFT** [comment]
Once we're happy with the pattern I intend on porting it to the product repos.

**Comment by ChadNedzlek** [comment]
Whew. That is a mouthful on the line. But given we're writing a CMD file, we don't have a ton of options, I guess. LGTM

**Comment by weshaggard** [comment]
Sigh... I really don't like seeing all this extra logic being included here. Can we look to see if there is any existing API or way to download a file on windows that supports retrying directly.

**Comment by markwilkie** [comment]
There are APIs that Azure publishes, but they don't support core (yet).  Perhaps as an interim step is to create our own mini-tool set that we publish in build tools to interact with Azure.

**Comment by weshaggard** [comment]
@markwilkie unfortunately I don't think that will help much in this case as this is the initial bootstraping code to pull down the CLI from Azure blob which we need in order to do the restoring of build tools. Whatever we use he has to already be on the system.

**Comment by markwilkie** [comment]
@weshaggard, true.  But at least we can relegate that duplication to bootstrapping code.  The right longer term solution is to use a published API.  Until that's ready, we might should think about putting our own placeholder in.

**Comment by jhendrixMSFT** [comment]
@weshaggard @markwilkie If we want to go the tool route then I would suggest we use wget for Windows as it already has retry logic baked in (i.e. let's not reinvent the wheel; we do this on Linux with great success).  Of course we still need to figure out how to get wget on the machine to begin with.

**Pull request merged**
