### PR TITLE
Use TagetGroup Filtering property instead of TargetGroup

### PR DESCRIPTION
**Pull request by tarekgh**
FilterToTargetGroup is the property we'll use to filter on TargetGroup. for the desktop we'll have FilterToTargetGroup=net46

### CODE REVIEW

**Comment by tarekgh** [comment]
@MattGal @weshaggard  this is a small fix to use the filtering property instead of the TargetGroup

**Comment by tarekgh** [comment]
test Innerloop Windows Debug please

**Comment by MattGal** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
