### PR TITLE
Add Serviceable element to NuSpec

### PR DESCRIPTION
**Pull request by ericstj**
This change adds the Serviceable element to our NuSpecs with default of true.

The first change is preparing for the update.  Primarily just getting us off of
DNXCore50 in our one test project so that we don't have to add more imports hacks.
This new buildtools exposed some existing issues in our projects that I fixed.

The second change updates the NuGet version and fixes source break due to 
API breaking change in NuGet.

The last change is the actual fix.

/cc @joshfree @weshaggard

### CODE REVIEW

**Comment by schellap** [comment]
@ericstj after this change is merged, `coreclr`, `corefx` need to pick up this version of the buildtools to get the attribute, is that correct?

**Comment by ericstj** [comment]
Correct + WCF

**Comment by schellap** [comment]
It appears that you want to manage the attribute centrally here similar to RequireLicenseAcceptance and still allow package owners to opt out if they like. We don't need to change all repos, is that correct?

**Comment by ericstj** [comment]
Repos merely need to update the buildtools version. It isn't automatic.

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows Debug

**Comment by ericstj** [comment]
@mmitche Jenkins doesn't seem to want to restart this build, anything you can help with?

**Comment by schellap** [comment]
@eerhardt, please update build tools with this change in `core-setup`. This is necessary to produce packages that are marked serviceable.

**Comment by eerhardt** [comment]
what build number should we be using in core-setup?

**Comment by schellap** [comment]
I used 1.0.25-prerelease-00507-01 on the https://github.com/dotnet/buildtools page for internal testing.

However, I had to copy over `lib\tool-runtime\project.json` from the previous package because it was missing in the above package. This caused some build errors  during `dotnet-restore` when running `init-tools.cmd`. I edited the nuget version in this PR after copying the old PJ.

**Comment by weshaggard** [comment]
@schellap are you working on a BuildTools update for the core-setup repo? I had done some of that work as part of https://github.com/dotnet/core-setup/pull/14 which I can split out, if needed.

We also need to wait until @ericstj fix (https://github.com/dotnet/buildtools/pull/778) makes it into BuildTools.

**Comment by schellap** [comment]
@weshaggard, I plan to update the BuildToolsVersion.txt with new version once @ericstj fix #778 goes in. If you want to split that part out it is fine by me. I encountered no issues other than the PJ missing.

**Comment by ericstj** [comment]
Might be an issue, seeing this fail for CoreFx on OSX and Ubuntu.  https://github.com/dotnet/corefx/pull/9209

**Pull request merged**
