### PR TITLE
Add null check.

### PR DESCRIPTION
**Pull request by Priya91**
cc @maririos

### CODE REVIEW

**Comment by mellinoe** [comment]
Hm, seems kind of strange to pass null to a method called "ParseSettingValue". Can we rename the method or ensure null doesn't get passed into it? It looks like there's just two call sites, can we detect null in those places?

**Comment by maririos** [comment]
What is the case here? Could you please provide an example?

**Comment by Priya91** [comment]
> What is the case here? Could you please provide an example?

When a setting of target or internal valueType is used, there is no value for the key, so the Dictionary is storing default(string)=null for those cases.

**Comment by Priya91** [comment]
>Hm, seems kind of strange to pass null to a method called "ParseSettingValue". Can we rename the method or ensure null doesn't get passed into it? 
ParseSettingValue expects a string to parse. Null is in the subset of valid values a string can have.
> It looks like there's just two call sites, can we detect null in those places?
No, there are 3 call sites, and this condition gets hit from ```FindSettingValue``` method. This happens when the ```value.DefaultValue``` is null. This happens because the JsonDeserializer is returning null for empty strings.

**Comment by Priya91** [comment]
Ok after debugging with @maririos seems like i was using ```default``` instead of ```defaultValue``` object, and hence json was storing null for that.. After correcting that, this issue doesn't happen. Closing the PR.

**Pull request closed without merging**
