### PR TITLE
Adding option to enable  using shared assemblies for multi-file tests

### PR DESCRIPTION
**Pull request by joperezr**
cc: @danmosemsft @safern @tijoytom

### CODE REVIEW

**Comment by joperezr** [comment]
After this is in and ingested in corefx, I will set `EnableMultiFileILCTests` on that side for Release-x64 configurations.

**Comment by joperezr** [comment]
This PR replaces #1578

**Comment by tijoytom** [comment]
@joperezr I might be missing something here , where is the buildSharedAssembly part ?

**Comment by joperezr** [comment]
that will be in corefx so that we only do it once as you suggested in the other PR. But I need this in first, so that I can consume it in corefx PR.

**Comment by tijoytom** [comment]
@joperezr thanks , makes sense . Thanks for doing this ... @botaberg We should do this for x86 too ( leave out ARM for now since we there are lot for failure in ARM single file now)

**Pull request merged**
