### PR TITLE
Allow specifying metadata for skip reason.

### PR DESCRIPTION
**Pull request by Priya91**
cc @weshaggard @joperezr

### CODE REVIEW

**Comment by joperezr** [comment]
LGTM. is the idea to add the issue # as the reason?

**Comment by weshaggard** [comment]
LGTM as well. Should we do this for the other attributes?

**Comment by Priya91** [comment]
> is the idea to add the issue # as the reason?

Yes issue number or in general reason for different behavior, I find myself commenting a lot while applying this attribute.

**Comment by Priya91** [comment]
> Should we do this for the other attributes?

Haven't had a need to specify reason on applying other attributes as much as this one. We can add, but it will most probably not be used at all..

**Pull request merged**
