### PR TITLE
Simplify and move to the branch CI model

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by ellismg** [comment]
@mmitche Is there a reason this repository has release/1.0.0-rc2 and rel/1.0.0 branches now?  They don't make sense in buildtools.  Can the safely be deleted or does something upstream need them?

**Comment by mmitche** [comment]
@ellismg It was mainly a test.  Do we only need master here?

**Comment by mmitche** [comment]
@ellismg Actually don't delete them yet, I want to test that out with completing 
https://github.com/dotnet/dotnet-ci/issues/181

**Pull request merged**
