### PR TITLE
Xunit options

### PR DESCRIPTION
**Pull request by safern**
This is to allow people to pass additional options to xunit through msbuild.

cc: @weshaggard @danmosemsft

### CODE REVIEW

**Comment by danmosemsft** [comment]
https://github.com/dotnet/buildtools/issues/1275
https://github.com/dotnet/buildtools/pull/1462

**Comment by danmosemsft** [comment]
I don't think this is the right fix. The goal is to allow /p:XUnitOptions to work (as well as it would be nice to add the two custom properties I had in my PR for class and method in case folks want those). The problem is if you do this /pXunitOptions, all these lines appending to it, don't work because the command line value wins. This is by (bad, original) design of MSBuild.

To fix that, XUnitOptions needs to be dumped into some other property up front, say `<_XUnitOptions>`. From that point down all appending etc is on _XUnitOptions.

**Comment by safern** [comment]
Could you take a look at my latest commit? With that way we would have XunitAdditionalOptions, XunitMethodName and XunitClassName so that is easier for everyone so that they don't have to learn the xunit switches such as -method or -class. We could leave XunitOptions as proposed to be the one people uses through msbuild and rename the actual property as you propose. Which is the same I'm doing here but without renaming, so whichever you prefer.

**Comment by bartonjs** [comment]
I'd prefer to keep my motor memory of setting XunitOptions, and thus the property inside msbuild should be renamed.  Needing to learn a new way of doing the same task is always frustrating.

**Comment by weshaggard** [comment]
>I'd prefer to keep my motor memory of setting XunitOptions, and thus the property inside msbuild should be renamed. Needing to learn a new way of doing the same task is always frustrating.

I tend to agree. Just rename the one we use internally to _XunitOptions.

**Comment by safern** [comment]
Well I guess it is decided, the 3 of you agreed :) so I will update the PR.

**Comment by safern** [comment]
Updated the PR to have 3 options:
* XunitOptions
* XunitMethodName
* XunitMethodClass

Could you PTAL?

**Comment by safern** [comment]
> You might want to do a search for XunitOptions in other targets to make sure there aren't any other places.

Didn't actually know there where more targets that involved Xunit. Will verify before merging. Thanks for the heads up.

**Comment by safern** [comment]
There was an instance of XunitOptions in CodeCoverage.targets where it disables parallelization. I updated it to be _XunitOptions as well.

**Pull request merged**
