### PR TITLE
Check for token type before casting

### PR DESCRIPTION
**Pull request by JeremyKuhne**
On Linux I'm seeing

        "compile": {
          "ref/any/System.Collections.dll": {}
        },

instead of

        "compile": [
          "ref/any/System.Collections.dll"
        ],

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@weshaggard, @akoeplinger, @ericstj

**Comment by akoeplinger** [comment]
Hmm interesting, I'm curious why there'd be a difference, can you point me to a sample where I can see this myself? LGTM otherwise.

**Comment by JeremyKuhne** [comment]
@akoeplinger You can see it in the lock files that get created in the source directories. Well I can, anyway. :) It might possibly be the newer drop of DNU I've got causing this...

**Comment by akoeplinger** [comment]
@JeremyKuhne I'm still seeing the old format with the current DNU. Might causes by https://github.com/aspnet/Announcements/issues/24 on the newer ones?

**Comment by akoeplinger** [comment]
Yeah, the lock file format seems to have changed, with the latest DNX I'm seeing this on Windows as well in an unrelated DNX project:

```
        "compile": {
          "lib/dnx451/EntityFramework.Core.dll": {}
        },
```

**Comment by JeremyKuhne** [comment]
@jasonmalinowski

**Comment by ericstj** [comment]
seems reasonable to me, thanks for making it backwards compatible

**Comment by jasonmalinowski** [comment]
Yep, seems reasonable. Not yet sure if I'm going to pull these back into the internal copy yet since it might not need it there. @ericstj if that becomes a headache then I'll pull it in.

**Comment by ericstj** [comment]
@jasonmalinowski I think if it's showing up in latest DNX it's just a matter of time until that code makes it to Nuget.

**Comment by jasonmalinowski** [comment]
Oh, hmm, I already thought I had consumed that change internally but I guess not.

**Pull request merged**
